name: build
on: 
  push:
    branches: ["master"]
env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
permissions:
  contents: read

jobs: 
  build-csharp:
    runs-on: windows-latest
    outputs:
      artifact: ${{steps.artifact.outputs.artifact-id}}
      version: ${{steps.version.outputs.version}}
    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: build
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.GITHUB_WORKSPACE}}

    - name: upload artifact
      id: artifact
      uses: actions/upload-artifact@v7
      with:
        name: build-backend
        path: ./bin/${{env.BUILD_CONFIGURATION}}/x64